const LAUNCH_META=`
<meta name="description" content="Run a trillion-dollar Mars programme. Build fast, manage consequences, and race the verified leaderboard.">
<meta property="og:title" content="TRILLIONAIRE — Mars Race">
<meta property="og:description" content="Run a trillion-dollar Mars programme and compete on the verified Mars Race leaderboard.">
<meta property="og:url" content="https://trillionairethegame.com/">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://trillionairethegame.com/">
`;

const LAUNCH_UI=`
<style id="tr-launch-ui-style">
#tr-race-launch{position:fixed;z-index:2147483000;top:max(12px,env(safe-area-inset-top));right:max(12px,env(safe-area-inset-right));border:1px solid rgba(111,231,255,.55);border-radius:999px;background:rgba(6,12,18,.92);color:#dff9ff;font:800 12px/1 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.12em;padding:11px 14px;box-shadow:0 10px 28px rgba(0,0,0,.35),0 0 22px rgba(62,205,255,.12);backdrop-filter:blur(12px);cursor:pointer;text-transform:uppercase}
#tr-race-launch:hover{border-color:#a9f2ff;transform:translateY(-1px)}
#tr-race-launch .tr-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#67f2bd;box-shadow:0 0 10px #67f2bd;margin-right:8px;vertical-align:1px}
#tr-race-modal{position:fixed;z-index:2147483001;inset:0;display:none;place-items:center;background:rgba(1,4,8,.78);backdrop-filter:blur(9px);padding:12px}
#tr-race-modal[data-open="1"]{display:grid}
.tr-race-panel{width:min(920px,calc(100vw - 24px));max-height:calc(100dvh - 24px);overflow:hidden;border:1px solid rgba(111,231,255,.25);border-radius:22px;background:linear-gradient(180deg,rgba(13,22,32,.99),rgba(5,10,16,.99));box-shadow:0 28px 90px rgba(0,0,0,.65),inset 0 1px 0 rgba(255,255,255,.04);color:#eaf9ff;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.tr-race-head{display:flex;gap:12px;align-items:flex-start;justify-content:space-between;padding:20px 20px 14px;border-bottom:1px solid rgba(255,255,255,.07)}
.tr-race-kicker{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:#70e7ff;font-weight:800}.tr-race-title{font-size:clamp(23px,5vw,36px);line-height:1;margin:6px 0 8px;font-weight:900;letter-spacing:-.035em}.tr-race-sub{font-size:12px;color:#91a9b7;max-width:560px;line-height:1.45}.tr-race-close{border:1px solid rgba(255,255,255,.12);background:#101a24;color:#d9f5ff;border-radius:12px;width:40px;height:40px;font-size:22px;cursor:pointer;flex:0 0 auto}
.tr-race-tabs{display:flex;gap:8px;padding:13px 20px 0;overflow:auto}.tr-race-tab{white-space:nowrap;border:1px solid rgba(255,255,255,.1);background:#0a131c;color:#8ca5b5;border-radius:999px;padding:9px 12px;font-size:11px;font-weight:800;letter-spacing:.05em;cursor:pointer}.tr-race-tab[data-active="1"]{color:#e9fbff;border-color:rgba(94,225,255,.55);background:rgba(36,167,206,.15);box-shadow:inset 0 0 18px rgba(55,202,255,.06)}
.tr-race-last{margin:13px 20px 0;padding:12px 14px;border:1px solid rgba(103,242,189,.22);border-radius:14px;background:rgba(33,117,90,.09);display:none;gap:10px;align-items:center;justify-content:space-between}.tr-race-last[data-show="1"]{display:flex}.tr-race-last strong{font-size:13px}.tr-race-last span{font-size:11px;color:#8fb7aa}.tr-race-rankchip{font-size:20px!important;font-weight:900!important;color:#86f8cf!important}
.tr-race-content{padding:13px 20px 20px;overflow:auto;max-height:calc(100dvh - 230px)}.tr-race-status{padding:28px 6px;text-align:center;color:#7f98a8;font-size:12px}.tr-race-tablewrap{overflow:auto;border:1px solid rgba(255,255,255,.07);border-radius:15px}.tr-race-table{width:100%;border-collapse:collapse;min-width:670px}.tr-race-table th{position:sticky;top:0;background:#0c151e;color:#76909f;text-align:left;font-size:9px;letter-spacing:.14em;text-transform:uppercase;padding:11px 12px;border-bottom:1px solid rgba(255,255,255,.08)}.tr-race-table td{padding:12px;font-size:12px;border-bottom:1px solid rgba(255,255,255,.055);color:#cce0ea}.tr-race-table tr:last-child td{border-bottom:0}.tr-race-table tr[data-own="1"]{background:linear-gradient(90deg,rgba(49,210,164,.13),rgba(64,195,243,.05));box-shadow:inset 3px 0 0 #67f2bd}.tr-race-pos{font-weight:950;color:#f2fbff}.tr-race-handle{font-weight:850;color:#f0fbff;letter-spacing:.03em}.tr-race-muted{color:#728b99!important}.tr-race-won{color:#7af2c4!important}.tr-race-lost{color:#ff9f9f!important}.tr-race-foot{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:11px 20px 16px;color:#667d8b;font-size:10px;border-top:1px solid rgba(255,255,255,.05)}
#tr-race-toast{position:fixed;z-index:2147483002;left:50%;bottom:max(16px,env(safe-area-inset-bottom));transform:translate(-50%,120%);opacity:0;width:min(620px,calc(100vw - 24px));border:1px solid rgba(103,242,189,.36);border-radius:18px;background:rgba(5,13,18,.97);box-shadow:0 22px 70px rgba(0,0,0,.58);color:#effcff;padding:15px;transition:transform .3s ease,opacity .3s ease;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#tr-race-toast[data-show="1"]{transform:translate(-50%,0);opacity:1}.tr-toast-top{display:flex;gap:12px;justify-content:space-between;align-items:flex-start}.tr-toast-rank{font-size:31px;line-height:1;font-weight:950;letter-spacing:-.04em;color:#7bf2c4}.tr-toast-copy strong{display:block;font-size:14px;margin-bottom:3px}.tr-toast-copy span{font-size:11px;color:#86a0ad}.tr-toast-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.tr-toast-actions button{border:1px solid rgba(255,255,255,.12);border-radius:10px;background:#101a23;color:#dbf6ff;padding:9px 11px;font-size:10px;font-weight:850;letter-spacing:.05em;cursor:pointer}.tr-toast-actions button:first-child{border-color:rgba(97,227,255,.45);background:rgba(34,157,196,.13)}
@media(max-width:640px){#tr-race-launch{top:auto;bottom:max(12px,env(safe-area-inset-bottom));padding:10px 12px}.tr-race-head{padding:17px 15px 12px}.tr-race-tabs{padding:11px 15px 0}.tr-race-last{margin:11px 15px 0}.tr-race-content{padding:11px 15px 16px;max-height:calc(100dvh - 220px)}.tr-race-foot{padding:10px 15px 14px}.tr-race-panel{border-radius:17px}.tr-race-sub{font-size:11px}}
</style>
<button id="tr-race-launch" type="button" aria-haspopup="dialog" aria-controls="tr-race-modal"><span class="tr-dot"></span>Mars Race</button>
<div id="tr-race-modal" role="dialog" aria-modal="true" aria-labelledby="tr-race-title">
  <section class="tr-race-panel">
    <header class="tr-race-head"><div><div class="tr-race-kicker">Verified competition · COMP-1.2</div><h2 class="tr-race-title" id="tr-race-title">MARS RACE</h2><div class="tr-race-sub">Every ranked run is replayed server-side before it reaches the board. Browser claims are not accepted on trust.</div></div><button class="tr-race-close" id="tr-race-close" type="button" aria-label="Close leaderboard">×</button></header>
    <nav class="tr-race-tabs" aria-label="Leaderboard boards"><button class="tr-race-tab" data-board="canonical" data-active="1" type="button">Canonical Score</button><button class="tr-race-tab" data-board="fastest" type="button">Fastest Mars</button><button class="tr-race-tab" data-board="efficient" type="button">Capital Efficiency</button></nav>
    <div class="tr-race-last" id="tr-race-last"><div><strong id="tr-race-last-title">Your last verified run</strong><br><span id="tr-race-last-copy"></span></div><span class="tr-race-rankchip" id="tr-race-last-rank"></span></div>
    <main class="tr-race-content"><div id="tr-race-status" class="tr-race-status">Loading verified runs…</div><div id="tr-race-table"></div></main>
    <footer class="tr-race-foot"><span id="tr-race-count">Season S01-W01</span><span>Server replay verified</span></footer>
  </section>
</div>
<div id="tr-race-toast" role="status" aria-live="polite"><div class="tr-toast-top"><div class="tr-toast-copy"><strong>VERIFIED MARS RACE RESULT</strong><span id="tr-toast-detail"></span></div><div class="tr-toast-rank" id="tr-toast-rank"></div></div><div class="tr-toast-actions"><button id="tr-toast-board" type="button">VIEW LEADERBOARD</button><button id="tr-toast-share" type="button">SHARE RESULT</button><button id="tr-toast-again" type="button">PLAY AGAIN</button></div></div>
<script id="tr-launch-ui-script">
(()=>{
'use strict';
const modal=document.getElementById('tr-race-modal');
const status=document.getElementById('tr-race-status');
const tableHost=document.getElementById('tr-race-table');
const countEl=document.getElementById('tr-race-count');
const lastBox=document.getElementById('tr-race-last');
const nativeFetch=window.fetch.bind(window);
let currentBoard='canonical';
let lastResult=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>Number.isFinite(Number(v))?'$'+Number(v).toFixed(1)+'B':'—';
function stored(){try{return JSON.parse(localStorage.getItem('trillionaire_last_ranked_run')||'null')}catch{return null}}
function showLast(){const x=lastResult||stored();if(!x||!x.run){lastBox.dataset.show='0';return}document.getElementById('tr-race-last-rank').textContent='#'+x.rank;document.getElementById('tr-race-last-copy').textContent=(x.run.handle||'YOUR RUN')+' · '+Number(x.run.score||0).toLocaleString()+' pts · '+(x.run.completion||('Turn '+x.run.turn));lastBox.dataset.show='1'}
function rowCells(r,board){if(board==='fastest')return '<td class="tr-race-pos">#'+r.rank+'</td><td class="tr-race-handle">'+esc(r.handle)+'</td><td>'+(r.completion?esc(r.completion):'Turn '+r.turn)+'</td><td>'+Number(r.score||0).toLocaleString()+'</td><td>'+esc(r.dependency)+'%</td><td>'+money(r.capital)+'</td>';if(board==='efficient')return '<td class="tr-race-pos">#'+r.rank+'</td><td class="tr-race-handle">'+esc(r.handle)+'</td><td>'+money(r.capital)+'</td><td>'+Number(r.score||0).toLocaleString()+'</td><td>'+(r.completion?esc(r.completion):'Turn '+r.turn)+'</td><td>'+esc(r.dependency)+'%</td>';return '<td class="tr-race-pos">#'+r.rank+'</td><td class="tr-race-handle">'+esc(r.handle)+'</td><td>'+Number(r.score||0).toLocaleString()+'</td><td>'+(r.completion?esc(r.completion):'Turn '+r.turn)+'</td><td class="'+(r.won?'tr-race-won':'tr-race-lost')+'">'+esc(r.grade||'—')+'</td><td>'+money(r.capital)+'</td>'}
function headers(board){if(board==='fastest')return '<th>Rank</th><th>Callsign</th><th>Mars</th><th>Score</th><th>Dependency</th><th>Capital</th>';if(board==='efficient')return '<th>Rank</th><th>Callsign</th><th>Capital</th><th>Score</th><th>Mars</th><th>Dependency</th>';return '<th>Rank</th><th>Callsign</th><th>Score</th><th>Mars</th><th>Grade</th><th>Capital</th>'}
async function loadBoard(board){currentBoard=board;status.style.display='block';status.textContent='Loading verified runs…';tableHost.innerHTML='';document.querySelectorAll('.tr-race-tab').forEach(b=>b.dataset.active=b.dataset.board===board?'1':'0');try{const res=await nativeFetch('/api/v1/leaderboards/current?board='+encodeURIComponent(board)+'&limit=25',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();countEl.textContent=(data.season||'Current season')+' · '+Number(data.count||0).toLocaleString()+' verified run'+(Number(data.count||0)===1?'':'s');if(!data.rows?.length){status.textContent='No verified runs yet. First clean Mars landing gets the empty board.';return}const mine=(lastResult||stored())?.id;const rows=data.rows.map(r=>'<tr data-own="'+(mine&&r.id===mine?'1':'0')+'">'+rowCells(r,board)+'</tr>').join('');tableHost.innerHTML='<div class="tr-race-tablewrap"><table class="tr-race-table"><thead><tr>'+headers(board)+'</tr></thead><tbody>'+rows+'</tbody></table></div>';status.style.display='none'}catch(e){status.style.display='block';status.textContent='Leaderboard link unavailable. The Mars bureaucracy has found a new form.';countEl.textContent='Connection error'}}
function openRace(board){modal.dataset.open='1';document.body.style.overflow='hidden';showLast();loadBoard(board||currentBoard)}
function closeRace(){modal.dataset.open='0';document.body.style.overflow=''}
async function shareResult(){const x=lastResult||stored();const r=x?.run;const text=r?'TRILLIONAIRE Mars Race: #'+x.rank+' · '+Number(r.score||0).toLocaleString()+' pts · '+(r.grade||'verified')+' · '+(r.architecture||'Mars programme')+' — can you beat it?':'TRILLIONAIRE Mars Race — can you beat the verified leaderboard?';const share={title:'TRILLIONAIRE — Mars Race',text,url:'https://trillionairethegame.com/leaderboard'};try{if(navigator.share){await navigator.share(share)}else if(navigator.clipboard){await navigator.clipboard.writeText(text+' https://trillionairethegame.com/leaderboard');document.getElementById('tr-toast-detail').textContent='Result copied to clipboard.'}}catch{}}
function playAgain(){const candidates=[...document.querySelectorAll('button,[role="button"],a')].filter(x=>!x.closest('#tr-race-modal')&&!x.closest('#tr-race-toast')&&x.id!=='tr-race-launch');const hit=candidates.find(x=>/play again|new run|fresh world|start over|restart/i.test((x.textContent||'').trim()));if(hit){hit.click();return}location.assign('/')}
function showRankToast(data){lastResult={id:data.id,rank:data.rank,run:data.run};try{localStorage.setItem('trillionaire_last_ranked_run',JSON.stringify(lastResult))}catch{}document.getElementById('tr-toast-rank').textContent='#'+data.rank;document.getElementById('tr-toast-detail').textContent=Number(data.run?.score||0).toLocaleString()+' pts · '+(data.run?.grade||'verified')+' · '+(data.run?.completion||('Turn '+data.run?.turn));const toast=document.getElementById('tr-race-toast');toast.dataset.show='1';setTimeout(()=>{if(toast.dataset.show==='1')toast.dataset.show='0'},15000)}
document.getElementById('tr-race-launch').addEventListener('click',()=>openRace('canonical'));document.getElementById('tr-race-close').addEventListener('click',closeRace);modal.addEventListener('click',e=>{if(e.target===modal)closeRace()});document.querySelectorAll('.tr-race-tab').forEach(b=>b.addEventListener('click',()=>loadBoard(b.dataset.board)));document.getElementById('tr-toast-board').addEventListener('click',()=>{document.getElementById('tr-race-toast').dataset.show='0';openRace('canonical')});document.getElementById('tr-toast-share').addEventListener('click',shareResult);document.getElementById('tr-toast-again').addEventListener('click',playAgain);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.dataset.open==='1')closeRace()});
window.TRILLIONAIRE_OPEN_LEADERBOARD=openRace;
window.fetch=async(...args)=>{const response=await nativeFetch(...args);try{const input=args[0];const url=typeof input==='string'?input:(input?.url||'');const init=args[1]||{};const method=String(init.method||input?.method||'GET').toUpperCase();if(method==='POST'&&/\/api\/v1\/runs(?:\?|$)/.test(url)){const data=await response.clone().json();if(data?.verified&&data?.rank&&data?.run)showRankToast(data)}}catch{}return response};
showLast();if(location.pathname==='/leaderboard'||new URLSearchParams(location.search).has('leaderboard'))setTimeout(()=>openRace('canonical'),120);
})();
</script>
`;

export function enhanceGameHtml(html,{build='v0.096'}={}){
  let out=String(html);
  out=out.replaceAll('v0.095',build);
  out=out.replace(/<title>[^<]*TRILLIONAIRE[^<]*<\/title>/i,'<title>TRILLIONAIRE — Mars Race</title>');
  if(out.includes('</head>'))out=out.replace('</head>',LAUNCH_META+'\n</head>');
  if(out.includes('</body>'))out=out.replace('</body>',LAUNCH_UI+'\n</body>');
  else out+=LAUNCH_UI;
  return out;
}
