import vm from 'node:vm';
import {ReplayEngine} from '../replay-engine.mjs';
import {loadGameHtml} from '../game-source.mjs';
const engine=ReplayEngine.fromHtml(await loadGameHtml());
const configs=[
 ['Solver A','supplier_equity',0.25],['Solver B','sovereign',0.35],['Solver C','supplier_equity',0.15],['Solver D','public_bond',0.30],['Solver E','none',0.10],
 ['Solver F','supplier_equity',0.45],['Solver G','sovereign',0.20],['Solver H','public_bond',0.15],['Solver I','supplier_equity',0.30],['Solver J','sovereign',0.40]
];
function ev(c,s){return vm.runInContext(s,c,{timeout:3000})}function ac(c){return engine.actions(c).length}function call(c,s){const b=ac(c);try{ev(c,s)}catch{}return ac(c)>b}
function snap(c){return ev(c,`(()=>({phase:state.phase,turn:state.turn,pending:!!state.pendingIncident,special:!!(SPECIALS[state.turn]&&!state.specialDone[state.turn]),cash:state.cash,debt:state.debt,systems:JSON.parse(JSON.stringify(state.systems||{})),built:JSON.parse(JSON.stringify(state.built||[])),pipeline:JSON.parse(JSON.stringify(state.pipeline||[])),selected:JSON.parse(JSON.stringify(state.selectedProjects||[])),flags:JSON.parse(JSON.stringify(state.flags||{})),dep:earthDependency()}))()`)}
function choose(c,riskBias){const ranked=ev(c,`(()=>{const b=new Set(Array.isArray(state.built)?state.built.map(x=>typeof x==='string'?x:x?.id):Object.keys(state.built||{}).filter(k=>state.built[k]));const q=new Set((state.pipeline||[]).map(x=>typeof x==='string'?x:x?.id));const sys=state.systems||{};const ratios=Object.fromEntries(Object.entries(TARGETS).map(([k,v])=>[k,Math.min(1.3,(sys[k]||0)/v)]));const ok=x=>!b.has(x.id)&&!q.has(x.id)&&!(x.excludes||[]).some(id=>b.has(id))&&(!x.chainAll||x.chainAll.every(id=>b.has(id)))&&(!x.chainAny||x.chainAny.some(id=>b.has(id)))&&(!x.req||Object.entries(x.req).every(([k,v])=>Number(sys[k]||0)>=Number(v)));const bonuses=new Set(['water','regolith','spares','closed_loop','greenhouse','machine_ecosystem','industrial_stack','closed_ecology','oxygen_fuel_complex','automated_mines','settlement_package','open_standard','boring_tests']);const score=x=>{let s=0;for(const [k,v] of Object.entries(x.effects||{})){const deficit=Math.max(.05,1-(ratios[k]||0));s+=Number(v||0)*(2.2+deficit*8)}s-=Number(x.risk||0)*100*${riskBias};s-=Number(x.cost||0)*.05;if(bonuses.has(x.id))s+=12;if(x.id==='crew_later'&&state.flags.crew===false&&state.turn>12)s+=35;return s};return PROJECTS.filter(ok).sort((a,z)=>score(z)-score(a)||a.cost-z.cost).slice(0,15).map(x=>x.id)})()`);let n=0;for(const id of ranked){if(n>=3)break;call(c,`toggleProject(${JSON.stringify(id)})`);n=snap(c).selected.length}if(snap(c).selected.length&&call(c,'commitPortfolio()'))return;call(c,'holdCycle089()')}
function run([name,finance,riskBias]){const c=engine.fresh();engine.startChallenge(c);let guard=0,stuck=null;while(snap(c).phase!=='ending'&&guard++<300){const s=snap(c),before=ac(c);try{if(s.pending)ev(c,'chooseIncident(2)');else if(s.phase==='incidentOutcome')ev(c,'continueAfterIncident()');else if(s.special){if(s.turn===12){const ready=(s.systems.launch+s.systems.habitat+s.systems.life+s.systems.reliability+s.systems.energy)/5;ev(c,`chooseSpecial(${ready>=58?0:1})`)}else ev(c,'chooseSpecial(2)')}else if(s.phase==='outcome')ev(c,'advance()');else if(s.phase==='event'){if(s.turn===0){call(c,"chooseDoctrine('procurement','open')");if(finance!=='none')call(c,`applyCapitalDeal('${finance}')`)}if(s.turn===1)call(c,"chooseDoctrine('execution','qualify')");if(s.turn===2)call(c,"chooseDoctrine('autonomy','review')");if(s.debt>=220)call(c,'repayDebt()');choose(c,riskBias)}else{stuck='phase '+s.phase;break}}catch(e){stuck=e.message;break}if(ac(c)===before&&snap(c).phase===s.phase&&snap(c).turn===s.turn){stuck='no progress';break}}
 const record=engine.record(c),actions=engine.actions(c),final=snap(c);let replayOk=false;try{const rr=engine.replay(actions);replayOk=JSON.stringify(rr.record)===JSON.stringify(record)}catch{}return{name,finance,riskBias,record,final,stuck,replayOk}}
const results=configs.map(run);console.log('SOLVER_SUMMARY '+JSON.stringify({runs:results.length,wins:results.filter(r=>r.record?.won).length,stuck:results.filter(r=>r.stuck).length,replayFailures:results.filter(r=>!r.replayOk).length}));for(const r of results){const x=r.record||{};console.log('SOLVER_RUN '+JSON.stringify({name:r.name,won:!!x.won,score:x.score,grade:x.grade,completion:x.completion,dependency:x.dependency,reliability:x.reliability,population:x.population,debt:x.debt,failures:x.failures,turn:x.turn,systems:r.final.systems,crew:!!r.final.flags?.crew,replayOk:r.replayOk,stuck:r.stuck}))}if(results.some(r=>r.stuck||!r.replayOk))process.exitCode=2;
